#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 19, 2020 12:45:20 AM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import addfriendpage_support


def vp_start_gui(main_client):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = addfriendpage(root)
    addfriendpage_support.init(root, top, main_client)
    root.mainloop()


w = None


def create_addfriendpage(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_addfriendpage(root, *args, **kwargs)' .'''
    global w, w_win, root
    # rt = root
    root = rt
    w = tk.Toplevel(root)
    top = addfriendpage(w)
    addfriendpage_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_addfriendpage():
    global w
    w.destroy()
    w = None


class addfriendpage:
    def check(self):
        # check if friend name entry is empty
        if self.friendnametxt.index("end") == 0:
            self.friendnametxt.configure(background="#FF8080")
            self.messagetxt['text'] = "can't be empty"
            return False
        self.messagetxt['text'] = ""
        self.friendnametxt.configure(background="white")
        return True

    def add_friend(self):
        if self.check():
            friend_name = self.friendnametxt.get()
            addfriendpage_support.add_friend(friend_name)

    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
           top is the toplevel containing window."""
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font9 = "-family {Arial Black} -size 9 -weight bold"

        top.geometry("281x137+501+189")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("Add friend")
        top.configure(background="#d9d9d9")

        self.friendnametxt = tk.Entry(top)
        self.friendnametxt.place(relx=0.463, rely=0.175, height=20, relwidth=0.406)
        self.friendnametxt.configure(background="white")
        self.friendnametxt.configure(disabledforeground="#a3a3a3")
        self.friendnametxt.configure(font="TkFixedFont")
        self.friendnametxt.configure(foreground="#000000")
        self.friendnametxt.configure(insertbackground="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.107, rely=0.175, height=16, width=84)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''friend's name''')

        self.addbutton = tk.Button(top)
        self.addbutton.place(relx=0.214, rely=0.584, height=34, width=67)
        self.addbutton.configure(activebackground="#ececec")
        self.addbutton.configure(activeforeground="#000000")
        self.addbutton.configure(background="#00a6ff")
        self.addbutton.configure(disabledforeground="#a3a3a3")
        self.addbutton.configure(font=font9)
        self.addbutton.configure(cursor="hand2")
        self.addbutton.configure(foreground="#000000")
        self.addbutton.configure(highlightbackground="#d9d9d9")
        self.addbutton.configure(highlightcolor="black")
        self.addbutton.configure(pady="0")
        self.addbutton.configure(text='''ADD''')
        self.addbutton.configure(command=self.add_friend)

        self.cancelbutton = tk.Button(top)
        self.cancelbutton.place(relx=0.605, rely=0.584, height=34, width=67)
        self.cancelbutton.configure(activebackground="#ececec")
        self.cancelbutton.configure(activeforeground="#000000")
        self.cancelbutton.configure(background="#00a6ff")
        self.cancelbutton.configure(disabledforeground="#a3a3a3")
        self.cancelbutton.configure(font=font9)
        self.cancelbutton.configure(cursor="hand2")
        self.cancelbutton.configure(foreground="#000000")
        self.cancelbutton.configure(highlightbackground="#d9d9d9")
        self.cancelbutton.configure(highlightcolor="black")
        self.cancelbutton.configure(pady="0")
        self.cancelbutton.configure(text='''Cancel''')
        self.cancelbutton.configure(command=addfriendpage_support.destroy_window)

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.messagetxt = tk.Label(top)
        self.messagetxt.place(relx=0.214, rely=0.365, height=21, width=174)
        self.messagetxt.configure(background="#d9d9d9")
        self.messagetxt.configure(disabledforeground="#a3a3a3")
        self.messagetxt.configure(foreground="#000000")
        self.messagetxt.configure(cursor="xterm")
