#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 30, 2020 11:00:20 PM +0300  platform: Windows NT

import sys
import client

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import loginpage_support


def vp_start_gui(main_client):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = loginPage (root)
    loginpage_support.init(root, top, main_client)
    root.mainloop()

w = None


def create_loginPage(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_loginPage(root, *args, **kwargs)' .'''
    global w, w_win, root
    # rt = root
    root = rt
    w = tk.Toplevel(root)
    top = loginPage(w)
    loginpage_support.init(w, top, *args, **kwargs)
    return w, top


def destroy_loginPage():
    global w
    w.destroy()
    w = None


class loginPage:
    def show_alert(self):
        self.loginalert.place(relx=0.268, rely=0.535, height=21, width=304)

    def clear(self):
        self.loginUserTxt.delete('0', 'end')
        self.loginPassTxt.delete('0', 'end')

    def check_user(self):
        # check if user entry is empty
        if self.loginUserTxt.index("end") == 0:
            self.loginUserTxt.configure(background="#FF8080")
            self.useremptyalert.place(relx=0.536, rely=0.301, height=21, width=124)
            return False
        self.loginUserTxt.configure(background="white")
        self.useremptyalert.place_forget()
        return True

    def check_pass(self):
        # check if password entry is empty
        if self.loginPassTxt.index("end") == 0:
            self.loginPassTxt.configure(background="#FF8080")
            self.passemptyalert.place(relx=0.536, rely=0.468, height=21, width=124)
            return False
        self.loginPassTxt.configure(background="white")
        self.passemptyalert.place_forget()
        return True

    def login(self):
        user_check = self.check_user()
        pass_check = self.check_pass()
        if user_check and pass_check:
            username = self.loginUserTxt.get()
            password = self.loginPassTxt.get()
            loginpage_support.login(username, password)

    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
           top is the toplevel containing window."""
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("522x299+394+161")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("Login")
        top.configure(background="#d9d9d9")

        self.usernameLable = tk.Label(top)
        self.usernameLable.place(relx=0.249, rely=0.227, height=18, width=60)
        self.usernameLable.configure(background="#d9d9d9")
        self.usernameLable.configure(disabledforeground="#a3a3a3")
        self.usernameLable.configure(foreground="#000000")
        self.usernameLable.configure(text='''Username''')

        self.passwordLable = tk.Label(top)
        self.passwordLable.place(relx=0.249, rely=0.401, height=17, width=60)
        self.passwordLable.configure(background="#d9d9d9")
        self.passwordLable.configure(disabledforeground="#a3a3a3")
        self.passwordLable.configure(foreground="#000000")
        self.passwordLable.configure(text='''Password''')

        self.loginUserTxt = tk.Entry(top)
        self.loginUserTxt.place(relx=0.536, rely=0.227, height=20, relwidth=0.326)
        self.loginUserTxt.configure(background="white")
        self.loginUserTxt.configure(cursor="xterm")
        self.loginUserTxt.configure(disabledforeground="#a3a3a3")
        self.loginUserTxt.configure(font="TkFixedFont")
        self.loginUserTxt.configure(foreground="#000000")
        self.loginUserTxt.configure(insertbackground="black")
        self.loginUserTxt.configure(text='''Create user''')
        self.loginUserTxt.configure(validate="focusout")
        self.loginUserTxt.configure(validatecommand=self.check_user)

        self.loginPassTxt = tk.Entry(top)
        self.loginPassTxt.place(relx=0.536, rely=0.401, height=20, relwidth=0.326)
        self.loginPassTxt.configure(background="white")
        self.loginPassTxt.configure(disabledforeground="#a3a3a3")
        self.loginPassTxt.configure(font="TkFixedFont")
        self.loginPassTxt.configure(foreground="#000000")
        self.loginPassTxt.configure(insertbackground="black")
        self.loginPassTxt.configure(show="*")
        self.loginPassTxt.configure(validate="focusout")
        self.loginPassTxt.configure(validatecommand=self.check_pass)

        self.loginButton = tk.Button(top)
        self.loginButton.place(relx=0.441, rely=0.635, height=34, width=67)
        self.loginButton.configure(activebackground="#ececec")
        self.loginButton.configure(activeforeground="#000000")
        self.loginButton.configure(cursor="hand2")
        self.loginButton.configure(background="#d9d9d9")
        self.loginButton.configure(disabledforeground="#a3a3a3")
        self.loginButton.configure(foreground="#000000")
        self.loginButton.configure(highlightbackground="#d9d9d9")
        self.loginButton.configure(highlightcolor="black")
        self.loginButton.configure(pady="0")
        self.loginButton.configure(text='''Login''')
        self.loginButton.configure(command=self.login)

        self.signupLink = tk.Button(top)
        self.signupLink.place(relx=0.268, rely=0.803, height=24, width=260)
        self.signupLink.configure(activebackground="#ececec")
        self.signupLink.configure(activeforeground="#000000")
        self.signupLink.configure(cursor="hand2")
        self.signupLink.configure(background="#d9d9d9")
        self.signupLink.configure(disabledforeground="#a3a3a3")
        self.signupLink.configure(foreground="#000000")
        self.signupLink.configure(highlightbackground="#d9d9d9")
        self.signupLink.configure(highlightcolor="#ff0000")
        self.signupLink.configure(pady="0")
        self.signupLink.configure(relief="flat")
        self.signupLink.configure(text='''Don't have a user? click here to create one now!''')
        self.signupLink.configure(command=loginpage_support.open_signup_page)

        self.loginalert = tk.Label(top)
        # self.loginalert.place(relx=0.268, rely=0.535, height=21, width=304)
        self.loginalert.configure(anchor='w')
        self.loginalert.configure(background="#d9d9d9")
        self.loginalert.configure(disabledforeground="#a3a3a3")
        self.loginalert.configure(foreground="#f5010a")
        self.loginalert.configure(text='''* username or password are incorrect''')

        self.useremptyalert = tk.Label(top)
        # self.useremptyalert.place(relx=0.536, rely=0.301, height=21, width=124)
        self.useremptyalert.configure(anchor='w')
        self.useremptyalert.configure(background="#d9d9d9")
        self.useremptyalert.configure(disabledforeground="#a3a3a3")
        self.useremptyalert.configure(foreground="#f5010a")
        self.useremptyalert.configure(text='''* please fill username''')

        self.passemptyalert = tk.Label(top)
        # self.passemptyalert.place(relx=0.536, rely=0.468, height=21, width=124)
        self.passemptyalert.configure(activebackground="#f9f9f9")
        self.passemptyalert.configure(activeforeground="black")
        self.passemptyalert.configure(anchor='w')
        self.passemptyalert.configure(background="#d9d9d9")
        self.passemptyalert.configure(disabledforeground="#a3a3a3")
        self.passemptyalert.configure(foreground="#f5010a")
        self.passemptyalert.configure(highlightbackground="#d9d9d9")
        self.passemptyalert.configure(highlightcolor="black")
        self.passemptyalert.configure(text='''* please fill password''')
