#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 31, 2020 04:17:38 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def init(top, gui, main_client, *args, **kwargs):
    global w, top_level, root, client
    w = gui
    top_level = top
    root = top
    client = main_client


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def user_button_click():
    global w, client
    w.userbutton['relief'] = 'sunken'
    w.technicianbutton['relief'] = 'raised'
    w.codetxt['state'] = 'disabled'
    client.tech_or_user = "u"


def tech_button_click():
    global w, client
    w.technicianbutton['relief'] = 'sunken'
    w.userbutton['relief'] = 'raised'
    w.codetxt['state'] = 'normal'
    client.tech_or_user = "t"


def connect():
    global w, client
    if client.tech_or_user == "t":
        client.code = w.codetxt.get()
    else:
        client.code = w.selfcode['text']
    client.start_connection()


if __name__ == '__main__':
    import mainpage
    mainpage.vp_start_gui()




