#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 30, 2020 11:53:11 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def init(top, gui, main_client, *args, **kwargs):
    global w, top_level, root, client
    w = gui
    top_level = top
    root = top
    client = main_client


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def open_login_page():
    global client
    destroy_window()
    client.open_login_page()


def sign_up(username, password, email):
    global client
    client.sign_up(username, password, email)


def failed_signup(user, eml):
    global w
    w.show_user_alert(eval(user), eval(eml))


if __name__ == '__main__':
    import signuppage
    signuppage.vp_start_gui()
