#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    May 30, 2020 01:32:10 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def init(top, gui, main_client, *args, **kwargs):
    global w, top_level, root, client
    w = gui
    top_level = top
    root = top
    client = main_client


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def yes_click():
    global client
    destroy_window()
    client.close = "yes"


def back_click():
    global client
    destroy_window()
    client.close = "back"


if __name__ == '__main__':
    import techalertmessage
    techalertmessage.vp_start_gui()




